### ISSUE TITLE
Questions about the full results with speaker follower

### ISSUE THREAD

**Issue by vincentlux** [arjunmajum/vln-bert#12]
Hi Arjun,

Thanks a lot for releasing the code! Is it possible that you can also share the code to reproduce the results in Table 3 of the paper? For example the way of combining with speaker follower models. Thanks in advance!

**Comment by arjunmajum** [comment]
@vincentlux 

Sorry for the delay.

Here is the code to combine VLN-BERT with the speaker and follower models from [1](https://arxiv.org/abs/1904.04195):

[combine-models.py](https://github.com/arjunmajum/vln-bert/blob/master/scripts/combine-models.py)

You can run it as follows:
```
python scripts/combine-models.py
--scores <path/to/results/scores_[val_seen|val_unseen].json>
--beam-scores data/beamsearch/scores_[val_seen|val_unseen].json>
```

This will produce the file: `<path/to/results/combined_scores_[val_seen|val_unseen].json>`, which you can pass to the [calculate-metrics.py](https://github.com/arjunmajum/vln-bert/blob/master/scripts/calculate-metrics.py) script:

```
python scripts/calculate-metrics.py <path/to/results/combined_scores_[val_seen|val_unseen].json>
```

Note: you may need to re-run the [download-auxiliary-data.py](https://github.com/arjunmajum/vln-bert/blob/master/scripts/download-auxiliary-data.py) script to get the beamsearch score files.

Also, here is the code that was used for grid-search to determine the hyperparameters used to combine the three models:

[grid-search.py](https://github.com/arjunmajum/vln-bert/blob/master/scripts/grid-search.py)
