### ISSUE TITLE
Access to trained model

### ISSUE THREAD

**Issue by g-jing** [arjunmajum/vln-bert#14]
VLN-BERT is great! I wonder if you could provide the trained model that could be used for evaluation?

**Comment by arjunmajum** [comment]
Thanks!

You can find trained model checkpoints here: [https://github.com/arjunmajum/vln-bert#model-zoo](https://github.com/arjunmajum/vln-bert#model-zoo)

Row 4 is the final model from the paper.

**Comment by g-jing** [comment]
Hi @arjunmajum. I thought Row 4 is the model after stage 3 pre-training and before downstream dataset fine-tuning. Does this mean the stage 3 pre-training means fine-tuning on R2R dataset in your paper?

**Comment by arjunmajum** [comment]
Yes, exactly. The model checkpoints in the table have already been fine-tuned on R2R.

**Comment by g-jing** [comment]
Hi @arjunmajum . Thanks so much for your explanation! Do you have the plan to release the model after stage 3 pre-training and before fine-tuning?
