### ISSUE TITLE
Reproducing resources requirement

### ISSUE THREAD

**Issue by g-jing** [arjunmajum/vln-bert#15]
Hi, I am trying to reproduce the work from the scratch. I used it on 24GB titan rtx and it is out of memory. May I ask what resources are required? Like how many GPU hours and what type of GPU.

**Comment by arjunmajum** [comment]
On a single GPU you would need to increase the number of gradient accumulation steps to avoid the memory issue, but training might take a long time.

We trained on a server with 8 x Titian X GPUS that each had 12 GBs of RAM. Finetuning the model took us ~23 hours.
